server:
  port: 9000
  shutdown: graceful
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/register
    username: root
    password: dbpassword
  jpa:
    hibernate:
      ddl-auto: update